<a href="https://colab.research.google.com/github/Sohamch03/Credit-Card-Fraud-Detection/blob/main/Credit_Card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Importing Libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
# loading the dataset to a pandas dataframe
credit_card_data = pd.read_csv("/content/creditcard.csv")

In [ ]:
# first 5 rows of the dataset
credit_card_data.head(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
13949,24754,1.252924,-0.182189,-0.802716,-0.210981,1.916713,3.643624,-0.778711,0.818295,1.706962,...,-0.497088,-1.211285,0.043809,0.964159,0.442030,0.261483,-0.051402,0.005112,23.74,0.0
13950,24756,-0.346979,-2.103284,-0.685061,1.961605,-0.401125,0.473632,1.133816,-0.256528,0.893409,...,0.359662,-0.316275,-0.864259,-0.279881,0.491802,-0.353996,-0.149931,0.129795,794.20,0.0
13951,24759,-6.053652,-5.988723,0.810413,-0.011811,1.308135,-0.590803,-0.725838,-0.234840,1.624646,...,-0.771970,1.474668,3.176363,-0.302410,0.052529,-0.373871,-0.700463,2.508443,60.00,0.0
13952,24759,1.169121,-1.284945,0.032717,-0.681670,0.660598,4.412578,-1.913115,1.076592,1.501230,...,-0.557596,-0.882435,-0.041523,0.975445,0.297229,0.550515,0.015029,0.032067,90.00,0.0
13953,24759,-6.917152,5.854171,-1.652458,-1.488884,-0.833891,-0.344418,0.393789,0.379968,6.133597,...,-1.404681,-1.124694,0.174333,-0.528234,0.990685,-0.035875,1.071374,-0.168831,NaN,NaN

In [ ]:
# dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13954 entries, 0 to 13953
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    13954 non-null  int64
 1   V1      13954 non-null  float64
 2   V2      13954 non-null  float64
 3   V3      13954 non-null  float64
 4   V4      13954 non-null  float64
 5   V5      13954 non-null  float64
 6   V6      13954 non-null  float64
 7   V7      13954 non-null  float64
 8   V8      13954 non-null  float64
 9   V9      13954 non-null  float64
 10  V10     13954 non-null  float64
 11  V11     13954 non-null  float64
 12  V12     13954 non-null  float64
 13  V13     13954 non-null  float64
 14  V14     13954 non-null  float64
 15  V15     13954 non-null  float64
 16  V16     13954 non-null  float64
 17  V17     13954 non-null  float64
 18  V18     13954 non-null  float64
 19  V19     13954 non-null  float64
 20  V20     13954 non-null  float64
 21  V21     13954 non-null  float64
 22  V22     13954 non-null  float64
 23  V23     13954 non-null  float64
 24  V24     13954 non-null  float64
 25  V25     13954 non-null  float64
 26  V26     13954 non-null  float64
 27  V27     13954 non-null  float64
 28  V28     13954 non-null  float64
 29  Amount  13953 non-null  float64
 30  Class   13953 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 3.3 MB

In [ ]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    1
Class     1
dtype: int64

In [ ]:
# distrinution of legit and fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0.0    13897
1.0       56
Name: count, dtype: int64

This dataset is highly unbalanced

0 ----> Normal Transaction

1 ----> Fraudulent Transaction

In [ ]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(13897, 31)
(56, 31)

In [ ]:
# statistical measures of the data

legit.Amount.describe()

count    13897.000000
mean        63.773909
std        177.164503
min          0.000000
25%          5.770000
50%         15.900000
75%         52.370000
max       7712.430000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count      56.000000
mean       90.815893
std       310.308450
min         0.000000
25%         1.000000
50%         1.000000
75%         1.025000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
# compare the values for both transaction
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,10111.481255,-0.217093,0.266252,0.887227,0.276789,-0.107510,0.136745,-0.131462,-0.020385,1.005460,...,0.020758,-0.068686,-0.158230,-0.034834,0.013065,0.117928,0.034349,0.009565,0.002329,63.773909
1.0,12262.107143,-4.727948,4.660436,-9.328536,6.783464,-2.890388,-2.030360,-6.578337,1.028374,-2.981468,...,0.453283,0.116896,0.048132,-0.225526,-0.452514,-0.124184,0.333325,0.793484,-0.046177,90.815893

# **Under-Sampling**

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> *492*

In [ ]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [ ]:
new_dataset = pd.concat([legit_sample,fraud],axis = 0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
2618,2149,1.260914,-0.120067,0.067540,-0.929421,-0.660411,-1.296634,0.017712,-0.151580,0.904143,...,0.096790,0.347785,-0.119004,0.533733,0.715261,-0.628089,0.030607,0.007710,1.00,0.0
10633,17867,-0.919907,-0.062145,1.135188,1.598653,2.110514,0.374202,-0.460292,0.202790,0.248964,...,0.141993,0.468635,-0.121279,-1.356356,-0.117831,-0.056238,0.138538,0.151061,6.00,0.0
8381,11217,-0.663532,0.078886,1.830175,0.074596,0.404242,-0.312217,-0.349665,0.175345,0.806177,...,-0.037299,-0.028443,0.148015,0.004911,-0.860875,0.941794,0.044850,0.133758,7.58,0.0
13131,23058,0.989457,-0.550424,1.180076,0.392415,-1.029669,0.098236,-0.708089,0.055249,2.306376,...,-0.177963,-0.240169,0.012003,0.116709,-0.007025,0.969370,-0.060348,0.024346,105.86,0.0
11185,19378,1.144455,-0.421195,1.017588,-0.672677,-0.966430,0.004188,-0.884230,0.212373,2.956095,...,-0.086397,0.187494,-0.006799,-0.039255,0.345384,-0.711293,0.072789,0.015361,10.85,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
11880,20451,-15.819179,8.775997,-22.804686,11.864868,-9.092361,-2.386893,-16.560368,0.948349,-6.310658,...,-2.350634,1.036362,1.136051,-1.043414,-0.108923,0.657437,2.136424,-1.411945,1.0,1.0
12070,20931,-16.367923,9.223692,-23.270631,11.844777,-9.462037,-2.450444,-16.925152,1.384208,-6.287736,...,-2.343674,1.004602,1.188212,-1.047184,-0.035573,0.664900,2.122796,-1.416741,1.0,1.0
12108,21046,-16.917468,9.669900,-23.736443,11.824990,-9.830548,-2.514829,-17.290657,1.820408,-6.264903,...,-2.336111,0.972755,1.241866,-1.051086,0.038009,0.672317,2.108471,-1.421243,1.0,1.0
12261,21419,-17.467710,10.114816,-24.202142,11.805469,-10.198046,-2.579938,-17.656788,2.256902,-6.242149,...,-2.328024,0.940830,1.296817,-1.055104,0.111792,0.679695,2.093541,-1.425491,1.0,1.0
12369,21662,-18.018561,10.558600,-24.667741,11.786180,-10.564657,-2.645681,-18.023468,2.693655,-6.219464,...,-2.319479,0.908839,1.352904,-1.059222,0.185751,0.687037,2.078081,-1.429517,1.0,1.0

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0     56
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,10001.160569,-0.126017,0.276096,0.912137,0.268430,-0.041525,0.183102,-0.128029,0.033568,0.959673,...,0.014817,-0.064339,-0.159927,-0.030758,0.020903,0.102128,0.034165,0.023893,-0.010757,53.080020
1.0,12262.107143,-4.727948,4.660436,-9.328536,6.783464,-2.890388,-2.030360,-6.578337,1.028374,-2.981468,...,0.453283,0.116896,0.048132,-0.225526,-0.452514,-0.124184,0.333325,0.793484,-0.046177,90.815893

Splitting the data into Features & Targets

In [ ]:
X = new_dataset.drop(columns='Class',axis = 1)
Y = new_dataset['Class']

In [ ]:
print(X)

        Time         V1         V2         V3         V4         V5        V6  \
2618    2149   1.260914  -0.120067   0.067540  -0.929421  -0.660411 -1.296634
10633  17867  -0.919907  -0.062145   1.135188   1.598653   2.110514  0.374202
8381   11217  -0.663532   0.078886   1.830175   0.074596   0.404242 -0.312217
13131  23058   0.989457  -0.550424   1.180076   0.392415  -1.029669  0.098236
11185  19378   1.144455  -0.421195   1.017588  -0.672677  -0.966430  0.004188
...      ...        ...        ...        ...        ...        ...       ...
11880  20451 -15.819179   8.775997 -22.804686  11.864868  -9.092361 -2.386893
12070  20931 -16.367923   9.223692 -23.270631  11.844777  -9.462037 -2.450444
12108  21046 -16.917468   9.669900 -23.736443  11.824990  -9.830548 -2.514829
12261  21419 -17.467710  10.114816 -24.202142  11.805469 -10.198046 -2.579938
12369  21662 -18.018561  10.558600 -24.667741  11.786180 -10.564657 -2.645681

              V7        V8        V9  ...       V20       V21       V22  \
2618    0.017712 -0.151580  0.904143  ... -0.178654  0.096790  0.347785
10633  -0.460292  0.202790  0.248964  ...  0.485999  0.141993  0.468635
8381   -0.349665  0.175345  0.806177  ...  0.195809 -0.037299 -0.028443
13131  -0.708089  0.055249  2.306376  ...  0.082611 -0.177963 -0.240169
11185  -0.884230  0.212373  2.956095  ... -0.217834 -0.086397  0.187494
...          ...       ...       ...  ...       ...       ...       ...
11880 -16.560368  0.948349 -6.310658  ...  0.992279 -2.350634  1.036362
12070 -16.925152  1.384208 -6.287736  ...  0.993585 -2.343674  1.004602
12108 -17.290657  1.820408 -6.264903  ...  0.996745 -2.336111  0.972755
12261 -17.656788  2.256902 -6.242149  ...  1.001519 -2.328024  0.940830
12369 -18.023468  2.693655 -6.219464  ...  1.007703 -2.319479  0.908839

            V23       V24       V25       V26       V27       V28  Amount
2618  -0.119004  0.533733  0.715261 -0.628089  0.030607  0.007710    1.00
10633 -0.121279 -1.356356 -0.117831 -0.056238  0.138538  0.151061    6.00
8381   0.148015  0.004911 -0.860875  0.941794  0.044850  0.133758    7.58
13131  0.012003  0.116709 -0.007025  0.969370 -0.060348  0.024346  105.86
11185 -0.006799 -0.039255  0.345384 -0.711293  0.072789  0.015361   10.85
...         ...       ...       ...       ...       ...       ...     ...
11880  1.136051 -1.043414 -0.108923  0.657437  2.136424 -1.411945    1.00
12070  1.188212 -1.047184 -0.035573  0.664900  2.122796 -1.416741    1.00
12108  1.241866 -1.051086  0.038009  0.672317  2.108471 -1.421243    1.00
12261  1.296817 -1.055104  0.111792  0.679695  2.093541 -1.425491    1.00
12369  1.352904 -1.059222  0.185751  0.687037  2.078081 -1.429517    1.00

[548 rows x 30 columns]

In [ ]:
print(Y)

2618     0.0
10633    0.0
8381     0.0
13131    0.0
11185    0.0
        ...
11880    1.0
12070    1.0
12108    1.0
12261    1.0
12369    1.0
Name: Class, Length: 548, dtype: float64

Split the data into Training data & Testing Data

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(548, 30) (438, 30) (110, 30)

# **Model Training**

# **Logistic Regression**

In [ ]:
model = LogisticRegression()

In [ ]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, Y_train)

KNeighborsClassifier()

In [ ]:
svm_model = SVC(kernel='linear', random_state=2)
svm_model.fit(X_train, Y_train)

SVC(kernel='linear', random_state=2)

In [ ]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=2)
rf_model.fit(X_train, Y_train)

RandomForestClassifier(random_state=2)

In [ ]:
dt_model = DecisionTreeClassifier(random_state=2)
dt_model.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=2)

# **Model Evaluation**

## **Accuracy Score**

In [ ]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9885844748858448

In [ ]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9545454545454546

In [ ]:

svm_predictions = svm_model.predict(X_test)
print("--- Support Vector Machine (SVM) ---")
print("Accuracy:", accuracy_score(Y_test, svm_predictions))
print("\nClassification Report:\n", classification_report(Y_test, svm_predictions))

--- Support Vector Machine (SVM) ---
Accuracy: 0.9636363636363636

Classification Report:
               precision    recall  f1-score   support

         0.0       0.99      0.97      0.98        99
         1.0       0.77      0.91      0.83        11

    accuracy                           0.96       110
   macro avg       0.88      0.94      0.91       110
weighted avg       0.97      0.96      0.96       110

In [ ]:

rf_predictions = rf_model.predict(X_test)
print("--- Random Forest ---")
print("Accuracy:", accuracy_score(Y_test, rf_predictions))
print("\nClassification Report:\n", classification_report(Y_test, rf_predictions))

--- Random Forest ---
Accuracy: 0.990909090909091

Classification Report:
               precision    recall  f1-score   support

         0.0       0.99      1.00      0.99        99
         1.0       1.00      0.91      0.95        11

    accuracy                           0.99       110
   macro avg       0.99      0.95      0.97       110
weighted avg       0.99      0.99      0.99       110

In [ ]:

knn_predictions = knn_model.predict(X_test)
print("--- K-Nearest Neighbors (KNN) ---")
print("Accuracy:", accuracy_score(Y_test, knn_predictions))
print("\nClassification Report:\n", classification_report(Y_test, knn_predictions))

--- K-Nearest Neighbors (KNN) ---
Accuracy: 0.9181818181818182

Classification Report:
               precision    recall  f1-score   support

         0.0       0.93      0.98      0.96        99
         1.0       0.67      0.36      0.47        11

    accuracy                           0.92       110
   macro avg       0.80      0.67      0.71       110
weighted avg       0.91      0.92      0.91       110

In [ ]:
dt_predictions = dt_model.predict(X_test)
print("--- Decision Tree ---")
print("Accuracy:", accuracy_score(Y_test, dt_predictions))
print("\nClassification Report:\n", classification_report(Y_test, dt_predictions))

--- Decision Tree ---
Accuracy: 0.9545454545454546

Classification Report:
               precision    recall  f1-score   support

         0.0       0.97      0.98      0.97        99
         1.0       0.80      0.73      0.76        11

    accuracy                           0.95       110
   macro avg       0.89      0.85      0.87       110
weighted avg       0.95      0.95      0.95       110